config/routes.rb
HolidayApp::Application.routes.draw do
  root  'sessions#new'

  resources :holidays do
    post 'accept', on: :member
    post 'decline', on: :member
  end

  resources :sessions

  resources :users

end

app/models/holiday.rb
class Holiday < ActiveRecord::Base
	belongs_to :user

	validate :user_has_holiday_remaining
	validates :start_date, presence: true
	validates :end_date,   presence: true
    validate :start_date_before_end_date



	def total_length
		return 0 unless start_date && end_date
		(end_date - start_date).to_i
	end

	def work_days
		return 0 unless start_date && end_date
		date_range = start_date..end_date

		date_range.sum { |d| ([0,6].include? d.wday) ? 0 : 1 }
	end

	def user_has_holiday_remaining
		return unless total_length > user.remaining_holiday_allowance

		errors.add(:base, "You have used up your holiday allowance")
	end

	def start_date_before_end_date
		return unless start_date > end_date
		errors.add(:base, "Start date cannot be later than the End date")
	end

	def accept!
      self.accepted = true
      save
    end
    def decline!
      self.accepted = false
      save
    end
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :signed_in_user

  # GET /holidays
  # GET /holidays.json
  def index
    @holiday = current_user.holidays.all
  end

  # GET /holidays/1
  # GET /holidays/1.json
  def show
  end

  # GET /holidays/new
  def new
    @user = current_user
    @holiday = current_user.holidays.build

    respond_to do |format|
      format.html
    end
  end

  # GET /holidays/1/edit
  def edit
    @holiday = Holiday.find params[:id]
  end

  # POST /holidays
  # POST /holidays.json
  def create
    @holiday = current_user.holidays.build(holiday_params)
    @holiday.start_date = Date.parse(params[:holiday][:start_date]) unless params[:holiday][:start_date].blank?
    @holiday.end_date = Date.parse(params[:holiday][:end_date]) unless params[:holiday][:end_date].blank?
    if @holiday.save
      flash[:success] = "holiday created!"
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  # PATCH/PUT /holidays/1
  # PATCH/PUT /holidays/1.json
  def update
     @holiday = Holiday.find params[:id]
    respond_to do |format|
      if @holiday.update(holiday_params)
        format.html { redirect_to current_user, notice: 'Holiday was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holidays/1
  # DELETE /holidays/1.json
  def destroy
       Holiday.find(params[:id]).destroy
    flash[:success] = "Holiday deleted."
    redirect_to current_user
  end

  def accept
    holiday = Holiday.find(params[:id])
    holiday.accept!
    redirect_to user_path(current_user)
  end

  def decline
    holiday = Holiday.find(params[:id])
    holiday.decline!
    redirect_to user_path(current_user)
  end

  private

    def holiday_params
      params.require(:holiday).permit(:start_date, :end_date)
    end
end

app/helpers/holidays_helper.rb
module HolidaysHelper

	def accepted_icon_for_holidays(holiday)
	content_tag :i, '', class: "icon-#{holiday.accepted ? 'ok' : 'remove'}",
	                    title: (holiday.accepted ? 'Yes' : 'No')
	end
end

app/views/holidays/_form.html.erb
<%= form_for(@holiday) do |f| %>
  <% if @holiday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@holiday.errors.count, "error") %> prohibited this holiday from being saved:</h2>

      <ul>
      <% @holiday.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/holidays/edit.html.erb
<%= form_for [@holiday] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.date_field :start_date, :placeholder => 'dd/mm/yyyy', class: 'datepicker' %>
    <%= f.date_field :end_date, :placeholder => 'dd/mm/yyyy', class: 'datepicker' %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/holidays/index.html.erb
<div class="span8">
      <h3>All Holidays</h3>
      <%= render 'shared/feed' %>
    </div>

app/views/holidays/new.html.erb
<%= form_for [@holiday] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.date_field :start_date, :placeholder => 'dd/mm/yyyy', class: 'datepicker' %>
    <%= f.date_field :end_date, :placeholder => 'dd/mm/yyyy', class: 'datepicker' %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/holidays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @holiday.user_id %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @holiday.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @holiday.end_date %>
</p>

<%= link_to 'Edit', edit_holiday_path(@holiday) %> |
<%= link_to 'Back', holidays_path %>