config/routes.rb
HolidayApp::Application.routes.draw do
  root  'sessions#new'

  resources :holidays do
    post 'accept', on: :member
    post 'decline', on: :member
  end

  resources :sessions

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :holiday

	STANDARD_WEEK_HOURS = 40.0

	STANDARD_HOLIDAY = 25.0

	HOLIDAYS_PER_MONTH = 25 / 12.0

	has_many :holidays, dependent: :destroy

	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
                      uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, unless: Proc.new { |u| u.password.blank? }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def total_holidays
		holidays.sum &:work_days
	end

	def holiday_allowance
    (standard_holiday + long_service_holiday).round
  end

  def remaining_holiday_allowance 
    (holiday_allowance - total_holidays)
  end

	def standard_holiday
		if start_date > Time.now.beginning_of_year
		  ((12 - start_month) * HOLIDAYS_PER_MONTH).round
		else
		  hours_per_week / STANDARD_WEEK_HOURS * STANDARD_HOLIDAY
		end
	end

  def long_service_holiday
    if start_date < 7.years.ago.beginning_of_year
      5 * hours_per_week / STANDARD_WEEK_HOURS
    elsif start_date < 6.years.ago.beginning_of_year
      4 * hours_per_week / STANDARD_WEEK_HOURS
    elsif start_date < 5.years.ago.beginning_of_year
      3 * hours_per_week / STANDARD_WEEK_HOURS
    elsif start_date < 4.years.ago.beginning_of_year
      2 * hours_per_week / STANDARD_WEEK_HOURS
    elsif start_date < 3.years.ago.beginning_of_year
      1 * hours_per_week / STANDARD_WEEK_HOURS
    else
      0
    end
  end

  def start_month
    start_date.month.to_i
  end
  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @holidays = @user.holidays.paginate(page: params[:page])
    @employee_holiday = Holiday.joins(:user).where('line_manager' == current_user.email)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
     @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Holiday App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
       flash[:success] = "Profile updated"
       redirect_to @user    
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private

  def user_params
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password_confirmation].blank?
    Rails.logger.warn params.inspect
    user_params = params.require(:user).permit(:name, :email, :start_date, :hours_per_week, :password, :password_confirmation)

    Rails.logger.warn user_params.inspect

    user_params
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  # Before filters

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_holidays.html.erb
<li>
  <span class="content"><%= holidays.start_date %></span>
  <span class="content"><%= holidays.end_date %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(holidays.created_at) %> ago.
  </span>
</li>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
  <h2>Total Holidays Taken = <%=user.total_holidays%> / <%=user.holiday_allowance%></h2>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :start_date %>
      <%= f.text_field :start_date %>

      <%= f.label :hours_per_week %>
      <%= f.text_field :hours_per_week %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>
      <br>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :start_date %>
      <%= f.text_field :start_date %>

      <%= f.label :hours_per_week %>
      <%= f.text_field :hours_per_week %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      <br>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span3">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>
<div class="span8">
    <% if @user.holidays.any? %>
      <h3>Holidays (<%= @user.holidays.count %>)</h3>
      <ol class="holidays">
        <% @holidays.each do |holiday| -%>
          <li><%=holiday.start_date%> - <%=holiday.end_date%> - <%=holiday.work_days%> Days Leave</li>
          <%= link_to 'Cancel Holiday', holiday_path(holiday),
            :confirm => 'Are you sure?', :method => :delete %>
            <%= link_to 'Edit Holiday', edit_holiday_path(holiday) %>
            <%=accepted_icon_for_holidays(holiday)%>
        <% end -%>
      </ol>
      <%= will_paginate @holidays %>

      <h3>Total number of holidays this year</h3>
      <%=@user.total_holidays%> / <%=@user.holiday_allowance%>
    <% end %>

    <br>
    <br>
    

    <%= link_to "Book Holiday!", new_holiday_path, class: "btn btn-large btn-primary" %>
    </div>
  </div>
</div>
<br><br>
<div >
  <h3>Employee Holidays</h3>
  <%if current_user.admin? %>
      <table border="1">
        <thead>
          <tr>
            <th>Employee</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Accept</th>
          </tr>
        </thead>
        <% @employee_holiday.each do |holiday|%>
          <tbody>
            <tr>
              <td><%=holiday.user.name%></td>
              <td><%=holiday.start_date%></td>
              <td><%=holiday.end_date%></td>
              <% if holiday.accepted? %>
                <td><%=button_to "Decline", decline_holiday_path(holiday), {class: "btn btn-danger", form: {style: 'margin:0px;'} } %><td>
              <%else%>
                <td><%=button_to "Accept", accept_holiday_path(holiday), {class: "btn btn-primary", form: {style: 'margin:0px;'} } %><td>
              <%end%>
            </tr>
          </tbody>
        <%end%>
      </table>
  <%end%>
</div>